### ISSUE TITLE
Logo Proposals

### ISSUE THREAD

**Issue by tony-go** [peerlinks/peerlinks-desktop#16]
Here two new ideas for the logo (just two different fonts) as we talk in the IRC channel :

![PL2](https://user-images.githubusercontent.com/22824417/65074438-1e1bbe80-d995-11e9-8ac9-f5664ff70377.png)

<img width="603" alt="Capture d’écran 2019-09-17 à 22 04 29" src="https://user-images.githubusercontent.com/22824417/65075779-d9455700-d997-11e9-9c8c-b51262b78cb3.png">

I let anyone pop some ideas ;)

**FYI** : _we trying to compare with the current logo :_ 
![peerlinks-desktop](https://raw.githubusercontent.com/peerlinks/peerlinks-desktop/master/Artwork/banner-slim-1280x360.png)

**Comment by tony-go** [comment]
With grade : 
<img width="603" alt="Capture d’écran 2019-09-17 à 22 04 29" src="https://user-images.githubusercontent.com/22824417/65075414-2b39ad00-d997-11e9-9f0b-da150798f7d7.png">

**Comment by heapwolf** [comment]
I dig these variations. I like the shadows the squares cast in the original one, would be interesting to see what that looks like on the circular version.

**Comment by achou11** [comment]
I still like the shapes used in the current one the most! The round ones remind me of Beaker's logo 😅 (not necessarily a bad thing)

**Comment by tony-go** [comment]
> I dig these variations. I like the shadows the squares cast in the original one, would be interesting to see what that looks like on the circular version.

@heapwolf  Here some shadows :)

<img width="817" alt="Capture d’écran 2019-09-18 à 06 52 29" src="https://user-images.githubusercontent.com/22824417/65112730-e89cc280-d9e0-11e9-9fc1-e2dedaa6d5b3.png">

@achou11 I gotcha :)

**Comment by joshmh** [comment]
I like the new logo ideas and I think the typography is better. I feel like the yellow "s" is too distracting, though. I like the pink dot on the "i". Maybe there's another way to incorporate a splash of yellow into the text, or maybe it's not necessary.

**Comment by tony-go** [comment]
> I like the new logo ideas and I think the typography is better. I feel like the yellow "s" is too distracting, though. I like the pink dot on the "i". Maybe there's another way to incorporate a splash of yellow into the text, or maybe it's not necessary.

Hi @joshmh :) Thanks for the feedback.

Here a version with the yellow "s" : 
<img width="486" alt="Capture d’écran 2019-09-18 à 21 48 56" src="https://user-images.githubusercontent.com/22824417/65180899-31469100-da5e-11e9-8739-04f7caaf8a25.png">

**Comment by joshmh** [comment]
Yeah, I like that best :)

**Comment by indutny** [comment]
I think it'd be best to stay with what we have right now. Let's return to this issue at some point, though!
