### ISSUE TITLE
Multiline for message in list

### ISSUE THREAD

**Issue by tony-go** [peerlinks/peerlinks-desktop#18]
The text area handle multi line input, but the value is not display as multi line in the feed.

![Sep-19-2019 23-22-13](https://user-images.githubusercontent.com/22824417/65282273-cd42cc00-db34-11e9-892b-0aa581fd7406.gif)

I can try to fix it :)

**Comment by indutny** [comment]
We currently render the messages as markdown. I think this is caused by this.
